
Running tests... 
----------------------------------------------------------------------
 test_1 (air_demo.WSTestcase) ... OK (11.203057)s
 test_2 (air_demo.WSTestcase) ... ERROR (2.153962)s

======================================================================
ERROR [2.153962s]: air_demo.WSTestcase.test_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/yangcong/PycharmProjects/unittest_Airtest/test_case/air_demo.py", line 36, in test_2
    raise '1111'
TypeError: exceptions must derive from BaseException

----------------------------------------------------------------------
Ran 2 tests in 0:00:13

FAILED
 (Errors=1)

Generating HTML reports... 
reports/TestResults_air_demo.WSTestcase_2019-12-24_18-48-39.html
